org.gradle.jvmargs=-Xmx3G
org.gradle.daemon=false

minecraft_version=1.19.2
forge_version=43.5.1
mapping_channel=official
mapping_version=1.19.2

mod_id=utilityscraft
mod_name=UtilitysCraft
mod_license=All Rights Reserved
mod_version=1.0.0
mod_group_id=com.utilityscraft
mod_authors=ScriptCreator109
mod_description=Utility items for Forge 1.19.2
