modLoader="javafml"
loaderVersion="[43,)"
license="All Rights Reserved"

[[mods]]
modId="utilityscraft"
version="1.0.0"
displayName="UtilitysCraft"
description='''
Utility items for Forge 1.19.2.
'''

[[dependencies.utilityscraft]]
    modId="forge"
    mandatory=true
    versionRange="[43,)"
    ordering="NONE"
    side="BOTH"

[[dependencies.utilityscraft]]
    modId="minecraft"
    mandatory=true
    versionRange="[1.19.2,1.20)"
    ordering="NONE"
    side="BOTH"
